import { rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { FileTransport } from "visual-storyboard/transports/file";
import { StoryboardWriter } from "visual-storyboard";

const rootDirectory = dirname(fileURLToPath(import.meta.url));
const publicDirectory = join(rootDirectory, "..", "public");
const outputFile = join(publicDirectory, "storyboards", "basic.ndjson");

const sampleScreenshot = (title: string, color: string) =>
  Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="960" height="540" viewBox="0 0 960 540">
      <rect width="960" height="540" fill="${color}" rx="28" />
      <rect x="60" y="70" width="840" height="400" fill="rgba(255,255,255,0.9)" rx="20" />
      <text x="100" y="170" font-family="system-ui, sans-serif" font-size="48" fill="#111827">${title}</text>
      <text x="100" y="240" font-family="system-ui, sans-serif" font-size="28" fill="#374151">Generated by the visual-storyboard sample workspace.</text>
    </svg>`,
  );

async function main() {
  await rm(join(publicDirectory, "storyboards"), { recursive: true, force: true });

  const writer = new StoryboardWriter({
    storyboardId: "Basic",
    transport: new FileTransport({ outputFile }),
  });

  await writer.createCheckpoint("Landing state", {
    imageBuffer: sampleScreenshot("Landing state", "#dbeafe"),
    imageContentType: "image/svg+xml",
    ariaSnapshot: '- document\n  - heading "Welcome" [level=1]\n  - button "Start"',
    highlights: [{ x: 120, y: 110, width: 280, height: 72, text: 'heading "Welcome"' }],
    viewport: { width: 960, height: 540 },
  });

  await writer.createCheckpoint("Menu open", {
    imageBuffer: sampleScreenshot("Menu open", "#ede9fe"),
    imageContentType: "image/svg+xml",
    ariaSnapshot: '- document\n  - navigation\n    - link "Dashboard"\n    - link "Settings"',
    highlights: [{ x: 90, y: 130, width: 220, height: 180, text: "navigation" }],
    viewport: { width: 960, height: 540 },
  });

  await writer.finalize();
}

await main();
